version: '2'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   php:
     depends_on:
       - db
     image: php:fpm
     volumes:
       - ./code:/code

   web:
      depends_on:
       - php
       - db
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
